import cProfile

stringz = (
    "CTXABNPSHKJTPOCCMXCJEJDGMEMSSXUWXTWJTTBEEHVFYIUQ"
    "QSPBZSJJEPMTOVNRHCIDZMFPNSVIOVEMFOOJMAVKQZLJUZCE"
    "YREOULNMRRSGEPCCWSONPQDJEEEFPAQRODMBPANTPVEUXYVY"
    "UITZEMMPQGDEMXUUMEUGGWYTIIUVHWTLPRNWCWNMKERDUTDF"
    "QELCLCTLJQRMRVYKOLVDSBRCTSKJOLZNKKMWASMQUVYENJFF"
    "MXECZDRIUWJQVFKKFRSFUESXTBJXGEOTVDBFXLEDFDSLPRHB"
    "HJCFXLKRHKQMJAAOEPMISWGAGOZZRZBPJFPXDHTXFTLREXAQ"
    "XCQXNEEULQPOMODJILDRLLEQXYSTKOYOQLKIBPECGTOCIEIP"
    "SLFQXSCQSBLXMKRCADDXCSMHGZAAGMMZYGHZHXJUXCTWXRZE"
    "TAIDJOVGMAQNWVBXPEQHINXAKARGFYCCOUAZOBGQMHSGSOEJ"
    "KMJHSMYWHDYPMVCQTJCNWDTFTFYRVZHDALMSYWNDXJHHHJLG"
    "FMFPVAROPDJAVPRYNHMIBHEWJCHFNPQKTCZPIARQFESJYOPS"
    "GLPWVRKCIQXWTBCGTEBWFWVGWRESMPMWXPYTLBGWPHEKEEVE"
    "RAMIHWWFKSIVHKHGAIWOVFHPYUAEDTIVYFEZEUGWMBFNOIIA"
    "JETAQAKTPRBQSOQXOQWYFKEEPKHLEAWTBXNLZXUSSZAKEAUG"
    "IKQTYREUZNFKMERBKUXMCMPFYTVHXCWOGAQXTTEAREZEJJLH"
    "SQCBEQQOMPCNNVSULBGHAOJWOEVLJGCJUQVHHFQIVLVLRFMT"
    "EJZVTCVBRFYQRSOYBPOAQLUIEAMIVVRAJTESMTTPLBKDJQQP"
    "WXJRSFGKNZTBIGNAMKEQWXCPAMWWHIIDQCLWCPFWVFQVZGWC"
    "WYLDDHZXIHWTRADNXCESONBFOEJACLMDNUWTUGRFSISKJYSP"
    "CCFPIAOFTUUCGJFBRYSINFXWUYTNVXQZRHNLKWWWNAGFUPQK"
    "LETXGPAHRTAWCRTQMSIEKKXBLJNRACCHHNKLVMPBSNKRDQIT"
    "IXNZMSRIYUVEGRYNKBHBAZCHLQMUEXBKPPWOUXUSPSVMDBVR"
    "VPMVJWBRNOBCPQOMQACGVMLBHYOSJWARJZHYNEESRIBPGBGY"
    "VVHZAFYVXKQAQAGLZVAXFPLASBJBTKHFMZGIFIRAQBTBSFGN"
)


def anti_vowel(text):
    new_text = []
    for i in text:
        if i not in "aeiouAEIOU":
            new_text.append(i)
    return "".join(new_text)


def repeat_code(code, string):
    for x in range(500000):
        eval("%s(%s)" % (code, string))


cProfile.run("repeat_code('anti_vowel', 'stringz')")
